import os
from building import *

cwd = GetCurrentDir()

# 核心驱动源文件（只编译实际需要的）
src = Split('''
board.c
drv_common.c
drv_clk.c
drv_gpio.c
drv_usart.c
drv_soft_i2c.c
drv_pwm.c
''')

path = [cwd]
path += [cwd + '/include']
path += [cwd + '/include/config']

# 添加 HAL 驱动和 CMSIS 头文件路径
path += [cwd + '/../libraries/STM32F4xx_HAL_Driver/Inc']
path += [cwd + '/../libraries/STM32F4xx_HAL_Driver/Inc/Legacy']
path += [cwd + '/../libraries/CMSIS/Device/ST/STM32F4xx/Include']
path += [cwd + '/../libraries/CMSIS/Include']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
